server:
  port: 8095

spring:
  application:
    name: live-classes-service

dynamodb:
  region: eu-north-1

eureka:
  client:
    service-url:
      defaultZone: http://172.18.2.70:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: ${JWT_SECRET}

videosdk:
  api:
    key: ${VIDEOSDK_API_KEY}
    secret: ${VIDEOSDK_SECRET}
    endpoint: https://api.videosdk.live/v2

aws:
  s3:
    bucket: kodemilabs-recordings
    region: eu-north-1
    accessKey: ${AWS_ACCESS_KEY}
    secretKey: ${AWS_SECRET_KEY}