server:
  port: 8095

spring:
  application:
    name: live-classes-service
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
      client:
        config:
          default:
            connectTimeout: 3000
            readTimeout: 5000

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      enrollmentClient:
        baseConfig: default
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 1s
        ignoreExceptions:
          - feign.FeignException.BadRequest
          - feign.FeignException.Unauthorized
    instances:
      enrollmentClient:
        baseConfig: default

dynamodb:
  region: eu-north-1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

jwt:
  secret: k8Jd9wQ2x+4aB3d1FJtL8vZ5X0yQ1V7n2gHqM4sP1tE=

videosdk:
  api:
    key: 9ea012b4-b6ff-4c9d-b7e1-644117bf5c94
    secret: 9091eade668321ecef4216ebd0516761742da5108f12caf5be4f206b2f58ae65
    endpoint: https://api.videosdk.live/v2

aws:
  s3:
    bucket: kodemilabs-recordings
    region: eu-north-1
    accessKey: ${AWS_ACCESS_KEY_ID:}
    secretKey: ${AWS_SECRET_ACCESS_KEY:}